language: r
cache: packages
latex: false
fortran: false
r_build_args: '--no-build-vignettes'

r: 3.4

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.3
      brew_packages: imagemagick
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode9.3
      brew_packages: imagemagick@6 --with-fontconfig --with-webp --with-librsvg
    - os: osx
      osx_image: xcode9.3
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
    - dist: trusty
      r_check_args: '--ignore-vignettes'
      addons:
        apt:
          packages:
            - libmagick++-dev
            - librsvg2-dev
            - libwebp-dev
            - libpoppler-cpp-dev
            - libtesseract-dev
            - libleptonica-dev
            - tesseract-ocr-eng
            - r-cran-rgdal
            - libfftw3-dev

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev

bioc_packages:
  - EBImage

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov(type = "all")'; fi

# Prevents Travis timeout for building magick
before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
